(defun get-solve(a b c)
  (let ((disc (- (* b b) (* 4 a c))))
    (cond ((= a 0)
	   (cond ((= b 0)
		  (cond ((= c 0) `x_any)
			(t `no_solutions)))
		 (t (/ (- c) b))))
	  (t (cond ((< disc 0) (cons (/ (- b) (* 2 a)) (/ (sqrt (abs disc)) (* 2 a))))
		   (t (cons (/ (+ (- b) (sqrt disc)) (* 2 a))
			    (cons (/ (- (- b) (sqrt disc)) (* 2 a)) nil))))))))
